### PR TITLE
use pretty material ui dialogs

### PR DESCRIPTION
**Pull request by Steffan153**
Changed it to use Material UI's `Dialog` instead of `prompt`/`confirm`.

https://deploy-preview-13--maxtodos.netlify.app/

### CODE REVIEW

**Comment by max-programming** [comment]
Looks more realistic now. Thank you 😀

**Comment by Steffan153** [comment]
I think I'll also do the drag and drop with react-beautiful-dnd. (unless material ui already has it)

**Comment by Steffan153** [comment]
Also the toasts, but in the same PR. I'll save the 4th one for another repo.

**Comment by max-programming** [comment]
Okay! Thanks a lot Caleb

**Pull request merged**
