### PR TITLE
Add a Hold Shift and click Delete to remove the delete confirmation

### PR DESCRIPTION
**Pull request by lucas-jg**

### CODE REVIEW

**Comment by max-programming** [comment]
Thanks a lot Lucas!!

**Comment by max-programming** [comment]
@all-contributors please add @lucas-jg for code

**Comment by lucas-jg** [comment]
Can you add a label to this PR? 
- hacktoberfest-accepted

**Comment by max-programming** [comment]
@lucas-jg TBH, there is no need to do that. As if the repo has the `hacktoberfest` topic. And the PR is merged. It will be accepted by Hacktoberfest. I'll also add the label if you want

**Comment by lucas-jg** [comment]
Thank you for your kind explanation.

**Pull request merged**
