### PR TITLE
Fix service worker

### LINKED ISSUE #24: Service Worker error in console. (404 not found)
need to fix this error in **Production mode**. Can't find serviceworker file
image

### PR DESCRIPTION
**Pull request by Steffan153**
Fixes #24. Looks like it's just the buggy react-scripts rc version. While I was at it I also updated to the newest react 17 version.

### CODE REVIEW

**Comment by Steffan153** [comment]
Huh, the netlify preview is complaining. It worked on my computer, I'll look at it

**Comment by Steffan153** [comment]
it's not working actually. is it okay if I add the React imports back? that's the only way out of this...

**Comment by max-programming** [comment]
Getting this error on the preview. And React 17 is now officially released. Not using the RC versions now
image

**Comment by Steffan153** [comment]
I said it was broken. The react-scripts was rc, not the react.

**Comment by max-programming** [comment]
Okay. Did you put the React Imports back? I think `react-scripts` needs to be at 4.0.0 to use JSX Transform.

**Comment by max-programming** [comment]
You're right. The SW issue is coming after I updated to React 17.  I think you should put back the React imports because you changed the version of  `react-scripts`

**Comment by Steffan153** [comment]
Alright, will do

**Comment by max-programming** [comment]
> Alright, will do
> Maybe you want to report this to the react bug thing?

Sure! Thanks!

**Comment by Steffan153** [comment]
done

**Comment by Steffan153** [comment]
nope wait

**Comment by max-programming** [comment]
@Steffan153 It does not use React. But it's imported 🤔

**Comment by Steffan153** [comment]
It complains if I don't add it and it complains if I add it. .

**Comment by Steffan153** [comment]
There we go. It worked now

**Comment by max-programming** [comment]
> It complains if I don't add it and it complains if I add it. .

Let's leave it as it is for now, I will create an issue on create-react-app about it. Should I close it?

**Comment by Steffan153** [comment]
you could merge it, idk

It was basically like "Hey!!!!!! We need react imported for this to work!!!!!!!!!!!!!!!!" but then when you add it eslint comes in like "nobody's using react"

**Comment by max-programming** [comment]
> you could merge it, idk
> 
> It was basically like "Hey!!!!!! We need react imported for this to work!!!!!!!!!!!!!!!!" but then when you add it eslint comes in like "nobody's using react"

lol. I'll merge it. But still React which is imported is not being used. Thanks!

**Comment by Steffan153** [comment]
well it's being used and not being used..... idk

**Comment by max-programming** [comment]
> well it's being used and not being used..... idk

It will be hopefull fixed when react-scripts 4.0.0 comes out

**Pull request merged**
