### PR TITLE
Fix long todo for mobile

### PR DESCRIPTION
**Pull request by worachatsun**
# Fix long todo for mobile, Truncate & refactor style used
Issue: https://github.com/max-programming/max-todos/issues/16

Screen Shot 2563-10-21 at 03 28 41

### CODE REVIEW

**Comment by max-programming** [comment]
Can you please make the Delete and Edit buttons be inline on desktop?

**Comment by worachatsun** [comment]
Please check it again.

**Comment by max-programming** [comment]
Do you have any warnings in the console? Fix those so that it can be deployed. Thanks a lot

**Comment by max-programming** [comment]
@worachatsun What warnings do you have. Can you please show them?

**Comment by max-programming** [comment]
And also, The checkbox acquires too much space on the desktop
image

**Comment by max-programming** [comment]
image
Still all of the checks have failed. :(

**Comment by worachatsun** [comment]
Nothing error in my console but in Netlify it errors when it builds. I will fix the spacing on the desktop version.

**Comment by max-programming** [comment]
Oh. @worachatsun Run `git pull` and `npm i` or `yarn`. Because I have switched to React 17.

**Comment by max-programming** [comment]
The checks failbecause I am using React 17 here

**Comment by worachatsun** [comment]
My repo is already React 17.
https://github.com/worachatsun/max-todos/blob/master/package.json

**Comment by max-programming** [comment]
> My repo is already React 17.
> https://github.com/worachatsun/max-todos/blob/master/package.json

So as I said, your repo is 5 commits behind mine.

**Comment by max-programming** [comment]
Sorry my bad. Your repo is 5 commits ahead of mine 😆

**Comment by max-programming** [comment]
Lemme create a new branch and i'll see what's wrong

**Pull request merged**
