### PR TITLE
New feature [Star]

### PR DESCRIPTION
**Pull request by worachatsun**
Screen Shot 2563-10-24 at 01 52 16

### CODE REVIEW

**Comment by max-programming** [comment]
Does starring push it to the top?

**Comment by max-programming** [comment]
image
btw, this is the warning

**Comment by max-programming** [comment]
Thank you so much!

**Comment by worachatsun** [comment]
Please wait. I have to fix some order logic.

**Comment by max-programming** [comment]
> Please wait. I have to fix some order logic.

You can create a new pull request now. It was merged and then reverted

**Comment by worachatsun** [comment]
@max-programming Could you please add `hacktoberfest-accepted` tag in my PR?

https://github.com/max-programming/max-todos/pull/28
https://github.com/max-programming/max-todos/pull/20
https://github.com/max-programming/max-todos/pull/19
https://github.com/max-programming/max-todos/pull/18
https://github.com/max-programming/max-todos/pull/26

**Comment by max-programming** [comment]
@worachatsun You don't need that label. As my repo has the `hacktoberfest` topic. And the PR is merged. It's accepted by hacktoberfest.
Read this: https://hacktoberfest.digitalocean.com/hacktoberfest-update
image

**Pull request merged**
