### PR TITLE
Added saving todos functionality. Todos are now stored in localstorage.

### PR DESCRIPTION
**Pull request by ychan052**
All todos should now be saved in localstorage upon addition/change/deletion.

### CODE REVIEW

**Comment by max-programming** [comment]
Do they get changed in the `localStorage` when we add, edit, delete???

**Comment by ychan052** [comment]
> Do they get changed in the `localStorage` when we add, edit, delete???

Yes, it should. The changes upon each addition, edit, or deletion can be viewed using the localStorage command in console, as well as on the actual Todo website. Let me know if it doesn't work on your end. I can try to look into it!

**Comment by max-programming** [comment]
I will merge it. I hope it works 😃

**Comment by max-programming** [comment]
It worked very nicely. Thanks for the contribution

**Comment by max-programming** [comment]
@all-contributors please add @ykchan052 for code

**Pull request merged**
